apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-info-service-default
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-info-service
      app.kubernetes.io/instance: devops-info-service-default
      app.kubernetes.io/component: web
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
