apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.configFileMapName" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
data:
  config.json: |-
{{ tpl (.Files.Get "files/config.json") . | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devops-info-service.configEnvMapName" . }}
  labels:
    {{- include "devops-info-service.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.config.application.name | quote }}
  APP_DEPLOY_ENV: {{ .Values.env.appEnv | quote }}
  APP_LOG_LEVEL: {{ .Values.config.settings.logLevel | quote }}
  APP_FEATURE_VISITS: {{ ternary "true" "false" .Values.config.featureFlags.visitsCounter | quote }}
  APP_CONFIG_RELOAD_STRATEGY: {{ .Values.config.settings.reloadStrategy | quote }}
